### ISSUE TITLE
首页显示Categories，而不是显示目录

### ISSUE THREAD

**Issue by dwqy** [gd4Ark/gd4Ark.github.io#42]
根目录_config.yml的language: zh-cn，但是首页还是显示Categories，不显示分类，是BUG么，谢谢

**Comment by dwqy** [comment]
@gd4Ark

**Comment by gd4Ark** [comment]
请问你是直接 fork 这个项目的吗？能不能提供更多有用的信息？
比如 hexo/themes/polarbear/_config.yml 和 hexo/themes/polarbear/languages/zh-cn.yml

**Comment by dwqy** [comment]
> 请问你是直接 fork 这个项目的吗？能不能提供更多有用的信息？
> 比如 hexo/themes/polarbear/_config.yml 和 hexo/themes/polarbear/languages/zh-cn.yml

我直接fork这个项目了，本地测试了，还是显示Categories，以下是 两个配置文件信息。
_config.yml
```
# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2018

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
    归档: /archives
    关于: /about
    订阅: /atom.xml

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
    Tags: true
    Categories: true
    Custom: false
    Friends: true

widget_custom:
    title: Slogan
    content: <p>Because we can</p>

friend_list:
    todebug: https://todebug.com
    MadLife: https://huangyongchi.com
    星空无限: https://liyangzone.com
    ydlan: https://blog.ydlan.cn
    野狼博客: https://www.sstype.com
    JerryC: https://jerryc.me
    25H's Blog: https://arae.cc
    wfxuni: https://www.wfxuni.com

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
    color: Default
    fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
    enable: false # gitment评论系统开关
    owner: gd4Ark # GitHub用户名
    repo: gd4Ark.github.io # 存储评论数据的GitHub仓库的仓库名
    client_id: ca4ae20760cf27ad5c6c # OAuth Application的Client ID
    client_secret: 671788fb8d6aed08906b70340a8ba3088ec03f39 # OAuth Application的Client Secret
    lazy: false # 评论懒加载开关

# Gitalk
# Introduction: https://github.com/gitalk/gitalk
gitalk:
    enable: true
    owner: gd4Ark # GitHub用户名
    repo: gd4Ark.github.io # 存储评论数据的GitHub仓库的仓库名
    client_id: ca4ae20760cf27ad5c6c # OAuth Application的Client ID
    client_secret: 671788fb8d6aed08906b70340a8ba3088ec03f39 # OAuth Application的Client Secret
    admin: ["gd4Ark"]
    distractionFreeMode: false
# ===========================================
# Version
# ===========================================
version: 1.1
```

zh-cn.yml
```
menu:
    home: 首页
    archives: 归档
    tags: 标签
    friends: 友链
    categories: 分类
    about: 关于

footer:
    powered: "Powered by %s"
    theme: 主题

posts:
    prev: 上一页
    next: 下一页
    prev_post: 上一篇
    next_post: 下一篇

counter:
    archives:
        zero: 暂无日志
        one: 目前共计 1 篇日志
        other: "目前共计 %d 篇日志"

    tagcloud:
        zero: 暂无标签
        one: 目前共计 1 个标签
        other: "目前共计 %d 个标签"

    categories:
        zero: 暂无分类
        one: 目前共计 1 个分类
        other: "目前共计 %d 个分类"

gitmentbutton: 显示Gitment评论
```
